<?php require_once 'config.php'; checkLogin(); include 'header.php';
$view_month = isset($_GET['m']) ? (int)$_GET['m'] : (int)date('m'); $view_year = isset($_GET['y']) ? (int)$_GET['y'] : (int)date('Y'); $today = date('Y-m-d');
if ($view_month < 1) { $view_month = 12; $view_year--; } if ($view_month > 12) { $view_month = 1; $view_year++; }
$first_day = mktime(0, 0, 0, $view_month, 1, $view_year); $days_in_month = date('t', $first_day); $offset = date('w', $first_day);
$sql_cal = "SELECT DATE(interview_datetime) as d, interview_datetime, company_name FROM jobs WHERE interview_datetime IS NOT NULL AND MONTH(interview_datetime) = ? AND YEAR(interview_datetime) = ? ORDER BY interview_datetime ASC";
$stmt_cal = $pdo->prepare($sql_cal); $stmt_cal->execute([$view_month, $view_year]); $cal_data = $stmt_cal->fetchAll(PDO::FETCH_GROUP|PDO::FETCH_ASSOC);
$pending = $pdo->query("SELECT j.* FROM jobs j JOIN statuses s ON j.status_id = s.id WHERE s.status_name = 'Applied' AND j.date_applied <= DATE_SUB(CURDATE(), INTERVAL 30 DAY)")->fetchAll();
$all_jobs = $pdo->query("SELECT j.*, s.status_name FROM jobs j JOIN statuses s ON j.status_id = s.id ORDER BY j.date_applied DESC LIMIT 15")->fetchAll(); ?>
<h1>Job Tracker Dashboard</h1>
<?php if ($pending): ?><div class="alert"><h3>Confirm Pending Rejections (30+ Days)</h3><?php foreach ($pending as $j): ?><p><strong><?= htmlspecialchars($j['company_name']) ?></strong> - <?= $j['date_applied'] ?> <a href="update_status.php?id=<?= $j['id'] ?>&status=Rejected&token=<?= $_SESSION['csrf_token'] ?>" style="color:#c53030; font-weight:bold;">[Confirm Rejection]</a></p><?php endforeach; ?></div><?php endif; ?>
<div class="calendar-card"><div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px;"><a href="?m=<?= $view_month-1 ?>&y=<?= $view_year ?>" class="btn">&laquo; Prev</a><h2><?= date('F Y', $first_day) ?></h2><a href="?m=<?= $view_month+1 ?>&y=<?= $view_year ?>" class="btn">Next &raquo;</a></div><div class="calendar-grid"><div class="calendar-header">SUN</div><div class="calendar-header">MON</div><div class="calendar-header">TUE</div><div class="calendar-header">WED</div><div class="calendar-header">THU</div><div class="calendar-header">FRI</div><div class="calendar-header">SAT</div>
<?php for($i=0; $i<$offset; $i++) echo '<div class="calendar-day" style="background:#f9f9f9;"></div>';
for($d=1; $d<=$days_in_month; $d++): $cur = sprintf("%04d-%02d-%02d", $view_year, $view_month, $d); $is_t = ($cur == $today); $s = $is_t ? "background:#fff9c4; border:2px solid #fbc02d;" : "background:white;"; ?>
<div class="calendar-day" style="<?= $s ?>"><strong><?= $d ?></strong><?php if(isset($cal_data[$cur])) foreach($cal_data[$cur] as $int) echo "<div class='cal-entry'>".date('g:i A',strtotime($int['interview_datetime']))."<br>".htmlspecialchars(substr($int['company_name'],0,15))."</div>"; ?></div><?php endfor; ?></div></div>
<h3>Recent Activity</h3><table><thead><tr><th>Date</th><th>Job Title</th><th>Company</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<?php foreach($all_jobs as $r): ?><tr><td><?= $r['date_applied'] ?></td><td><strong><a href="job_details.php?id=<?= $r['id'] ?>" style="color:#2b6cb0;"><?= htmlspecialchars($r['job_title']) ?></a></strong></td><td><?= htmlspecialchars($r['company_name']) ?></td><td><span class="status-badge status-<?= strtolower(str_replace(' ','-',$r['status_name'])) ?>"><?= $r['status_name'] ?></span></td><td><a href="job_form.php?id=<?= $r['id'] ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table><?php include 'footer.php'; ?>
